import type { Locale } from "./types";

const messages = {
  en: {
    loading: "Loading today’s shelves…",
    error: "The market could not be reached.",
    retry: "Try again",
    stale: "Showing a saved catalog — prices may have changed.",
    search: "Search the shelves",
    all: "All",
    empty: "No products found",
    emptyHint: "Try another search or category.",
    unavailable: "Unavailable",
    add: "Add",
    cart: "Your market ribbon",
    cartEmpty: "Your ribbon is empty",
    cartHint: "Add something from the shelves.",
    quantity: "Quantity for",
    remove: "Remove",
    total: "Total",
    checkout: "Order on WhatsApp",
    share: "Share shop",
    copied: "Link copied",
    language: "العربية",
    kicker: "Fresh from the counter",
    hero: "Good things, gathered close.",
  },
  ar: {
    loading: "نرتّب رفوف اليوم…",
    error: "تعذّر الوصول إلى المتجر.",
    retry: "حاول مجدداً",
    stale: "نعرض نسخة محفوظة — ربما تغيّرت الأسعار.",
    search: "ابحث في الرفوف",
    all: "الكل",
    empty: "لا توجد منتجات",
    emptyHint: "جرّب بحثاً أو تصنيفاً آخر.",
    unavailable: "غير متوفر",
    add: "أضف",
    cart: "شريط مشترياتك",
    cartEmpty: "شريطك فارغ",
    cartHint: "أضف شيئاً من الرفوف.",
    quantity: "الكمية لـ",
    remove: "احذف",
    total: "الإجمالي",
    checkout: "اطلب عبر واتساب",
    share: "شارك المتجر",
    copied: "تم نسخ الرابط",
    language: "English",
    kicker: "طازج من الدكّان",
    hero: "الطيّب جمعناه قريب.",
  },
} as const;

export const copy = (locale: Locale) => messages[locale];
